day8/re-com

src/re_com/validate.cljs
The validator for CSS styles had an extra colon.
=> Correct key for -webkit-user-select

run/resources/public/assets/css/re-com.css
`scroller` works in Chrome, but it seems to be because they haven't updated to the latest spec yet.
See this Firefox problem: http://stackoverflow.com/questions/28636832/firefox-overflow-y-not-working-with-nested-flexbox
The solution, considering `re-com` is going all-in on flexbox anyway, would be to set the minimum height and width to 0.
I can confirm it fixes the scrollers for Firefox.
=> Make re-com scrollers compatible with the spec

src/re_com/datepicker.cljs
`datepicker` supports a `:model` arg which is either a
`goog.date.UtcDateTime` or an atom containing one. `datepicker-dropdown`
claims the same, but calls `anchor-button`, which derefs it: this commit modifies
`anchor-button` so that `datepicker-dropdown` is true to its word.
=> datepicker-dropdown should deref-or-value model

src/re_com/buttons.cljs
- this improves the current behavior which can leave the tooltip
stranded on the screen
- but it doesn't allow any tooltip for a disabled button
- a better solution would allow the tooltip to show and hide properly
even when the button is disabled
- the issue of how to provide a tooltip for a disabled button has had a
fair amount of discussion online
- the usual advice is to wrap the button in a div and attach the
tooltip to that
- here's a representative discussion:
https://github.com/angular-ui/bootstrap/issues/1025
- I've been unable to get this to work for re-com's button, but
someone with more experience likely could
=> hide the tooltip when a button is disabled

src/re_com/datepicker.cljs
Hi,
At the moment, when navigating forwards or backwards for the month in a re-com datepicker, the clickable area is limited to the chevron icon. However, the entire button (th element) has a pointer cursor which means it can be quite confusing when trying to click forwards or backwards but nothing happens due to the cursor not being on the icon. This pull request fixes that problem.
=> Fix clickable area for month navigation chevron buttons in datepicker

src/re_com/dropdown.cljs, src/re_demo/dropdowns.cljs
This allows to provide custom markup while not messing with filtering. See #107.
=> Decouple label from rendering function in dropdown.

project.clj
Adds an optional lein profile for developing with Emacs+CIDER+piggieback as described [here](https://github.com/bhauman/lein-figwheel#scripting-figwheel)
=> add :dev-cider profile with piggieback for cider cljs repl

project.clj
Seeing this error when I include re-com `0.9.0` into my other project and try to 
build for prod with:
`lein clean && lein cljsbuild once min`
> Caused by: clojure.lang.ExceptionInfo: No such namespace: cljs.core.async, could not locate cljs/core/async.cljs, cljs/core/async.cljc, or Closure namespace "cljs.core.async" in file /home/travis/build/dviramontes/cfd-fn-talk/target/cljsbuild-compiler-1/re_com/typeahead.cljs {:tag :cljs/analysis-error}
You can see the full stack trace here:
https://travis-ci.org/dviramontes/cfd-fn-talk/builds/160884593
This fixed it for me but perhaps there is another way to solve it? 
Thanks!
=> fix missing core.async dependency error

src/re_com/selection_list.cljs
Now `true` or `false` is passed to checkbox rather than `nil` or `item-id`
=> Bug-fix for new reagent 0.6.0

src/re_com/datepicker.cljs
Removed the nil to empty string conversion as it does not seem to have any impact on the functionality. Fixes #132
=> Fix for when datepicker input model is nil.

src/re_com/dropdown.cljs
Super tiny PR to remove two`println` calls from `dropdown`  (https://dev.clojure.org/jira/browse/CLJS-2002).
Thank you very much for re-com!! 👍
=> Remove println

src/re_com/popover.cljs
Currently we can apply css style to the popover box, but cannot change the color of svg arrow.
This PR fixes it
=> Parametrize color of the svg arrow (stroke attribute)

src/re_com/datepicker.cljs, src/re_com/validate.cljs, src/re_demo/datepicker.cljs
Rename re-com.validate/goog-date? to date-like? and test arg via
cljs-time.core/date? which ensures it satisfies DateTimeProtocol instead
of concrete type checks. This allows consumers to provide their own
date like objects `e.g. day8.time.Date` which may not subclass goog.date.Date for :model,
:minimum & :maximum args.
=> datepicker: loosen model validation in datepicker to DateTimeProtocol

src/re_com/typeahead.cljs
Related to: https://github.com/Day8/re-com/issues/190
Whenever a user tries to tab out of a typeahead box, if the 2
conditions in the `and` of `re-com.typeahead/input-text-will-blur`
aren't met, then the local state-atom for typeahead is replaced with
`nil` instead of having its value updated. This causes the entire
component to just break.
=> Fix tabbing over typeahead elements

src/re_com/typeahead.cljs
Fixes #205
I've tested it in my own project, and all of the scenarios that I could think of work fine.
But please test it on your own as well.
=> Fix typeahead not taking external changes into account

run/resources/public/assets/css/re-com.css, src/re_com/dropdown.cljs, src/re_demo/dropdowns.cljs, test/re-com/dropdown_test.cljs
The new attributes:
* `:tooltip`             what to show in the tooltip
* `:tooltip-position`    relative to this anchor. One of :above-left, :above-center, :above-right, :below-left, :below-center, :below-right, :left-above, :left-center, :left-below, :right-above, :right-center, :right-below
* `:free-text?`          is the text freely editable? If true then :chocies is a vector of strings, :model is a string (atom) and :on-change is called with a string
* `:auto-complete?`      auto-complete text while typing using dropdown choices. Has no effect if :free-text? is not turned on
* `:capitalize?`         capitalize the first letter. Has no effect if :free-text? is not turned on
* `:enter-drop?`         should pressing Enter display the dropdown part? (true by default as this is the …
=> Add 15 new attributes and 1 fix to single-dropdown

src/re_com/misc.cljs, src/re_demo/input_text.cljs
It is called with the new value to alter it immediately.
See the `:on-alter` checkbox on the [updated demo page](https://pawelstroinski.github.io/re-com/#/input-text).
=> Add :on-alter to input-text-base

src/re_com/tabs.cljs, src/re_demo/tabs.cljs
The new attributes:
* `:tooltip-fn`          [horizontal-bar-tabs only] given an element of :tabs, returns its tooltip
* `:tooltip-position`    [horizontal-bar-tabs only] relative to this anchor. One of :above-left, :above-center, :above-right, :below-left, :below-center, :below-right, :left-above, :left-center, :left-below, :right-above, :right-center, :right-below
* `:validate?`           [horizontal-bar-tabs & vertical-bar-tabs only] validate :model against :tabs (true by default as this is the current behaviour)
The [Tooltips demo](https://pawelstroinski.github.io/re-com/#/tabs) has been added as well.
=> Add tooltip to horizontal-bar-tabs & :validate?

scripts/add-at-macro/src/add_at_macro/core.clj
Currently reading a file with an uneval form results in an error, `operation not permitted`. 
As rewrite-clj loops through files, it skips whitespaces and comments but does not skip uneval forms such as `#_[re-com.core ...]`. This makes it extremely hard for us to know if the current component we are looping is an uneval form or code to execute.
For example if we have the component
```Clojure 
[h-box
:size "1"
:children [#_[title :label "Hidden"]
[v-box :children []]
[box :child []]]]]]
```
If `rewrite-clj.zip/next` would skip uneval forms, we would've expected the next location, as we loop, to follow the path:
`[h-box ...]` -> `h-box` -> `:size` -> `"1"` -> `:children` -> `[#_[title ...]...]` -> `[v-box...]` -> `:children` -> `[]` -> etc
If `rewrite-clj` would have treated uneval forms …
=> Fix error when rewrite-clj reads uneval forms

scripts/add-at-macro/src/add_at_macro/core.clj, scripts/add-at-macro/test/add_at_macro/core_test.clj
=> Ignore `p` and `p-span` components in add at macro script

src/re_demo/title.cljs
Assuming that re-com is spelled all lower case, this is a typo.
=> Typo in title.cljs

src/re_demo/core.cljs
Assuming that re-com is spelled all lower case, this is a typo.
=> Typo in core.cljs

src/re_com/splits.cljs
=> Fix `h-split` and `v-split` split calculation in elements with `position : relative`

src/re_com/splits.cljs, src/re_demo/splits.cljs
=> Remove hardcoded `overflow` css  style in splits

src/re_com/alert.cljs
The alert boxes style is missing after 2.24.0 upgrade, specifically the style defined by the classes:
- alert-success
- alert-warning
- alert-danger
After a quick research what I can see is that in the namespace re-com.alert when setting the alert-class for the div of the alert-box, you use a piece of code like this in the let:
```
alert-class  (alert-type {:none           ""
:info           "alert-success"
:warning        "alert-warning"
:danger         "alert-danger"})
```
But it is not being properly called at
`(theme/merge-class "rc-alert" "alert" "fade in" "alert-class" class)
`
It should be:
`(theme/merge-class "rc-alert" "alert" "fade in" alert-class class)`
=> Fix: Alert box style missing

CHANGELOG.md, demo/re_demo/table_filter.cljs, src/re_com/table_filter.cljs, src/re_com/tag_dropdown.cljs
Add max-height parameter and default for tag-dropdown menu, give tag-dropdown tool within table-filter reasonable sizing defaults
=> Improve tag-dropdown sizing and defaults
